In [1]:
%matplotlib qt
from utils import FilePath
import hyperspy.api as hs
import numpy as np
import matplotlib.pyplot as plt
import atomap.api as am
from utils import FilePath
import scipy.ndimage as ndi
from skimage.restoration import rolling_ball
from skimage import feature
import h5py
import os

In [2]:
path = FilePath()
img = hs.load(path[0])

Now,b get 1 files
('G:/Code Projects/My_git_repos/MoWS2_Project/NAM/CrxW1-xS2_Gradient/Selected/20200723 1347 STEM Diffraction HAADF 5.5 Mx_HAADF.dm3',)


In [3]:
bkgimg = rolling_ball(img.data, radius=15)
nimg = img - bkgimg
fig, ax = plt.subplots(1, 2, sharey=True)
ax[0].imshow(nimg, 'gray')
ax[1].imshow(bkgimg, 'gray')
for i in ax:
    i.set_xticks([])
    i.set_yticks([])
fig.tight_layout()
fig.show()

In [4]:
p = feature.blob_dog(nimg, threshold=.025, min_sigma=1, max_sigma=30, overlap=.01)
fig2, ax2 = plt.subplots()
ax2.plot(p[:, 1], p[:, 0], 'ro', alpha=.4, lw=1)
ax2.imshow(img, 'gray')
ax2.axis('off')
fig2.show()

In [31]:
def manu_picks_to_(image, points, points_list, points_index, extent=[[0, 1024], [0, 1024]]):
    counts = 0
    def onpick(event):
        ind = event.ind
        global counts
        counts += 1
        points_list.append(points[:, ][ind])
        points_index.append(ind)
        print(f'onpick scatter no.{counts}:', ind, points[:, ][ind])

    fig, ax = plt.subplots()
    ax.plot(points[:, 1], points[:, 0], 'ro', alpha=.3, lw=1, picker=3)
    ax.imshow(image, 'gray')
    ax.axis('off')
    ax.set_xlim(extent[0])
    ax.set_ylim(extent[1])
    fig.canvas.mpl_connect('pick_event', onpick)
    fig.show()


In [6]:
rlist=[]
rind_list = []

In [7]:
manu_picks_to_(nimg, p, rlist, rind_list, extent=[[0, 512], [0, 512]])

onpick scatter: [2890] [[485.  12.   1.]]
onpick scatter: [3457] [[389.   0.   1.]]
onpick scatter: [3455] [[168.   4.   1.]]
onpick scatter: [3751] [[153.  11.   1.]]
onpick scatter: [4038] [[75.  7.  1.]]
onpick scatter: [3768] [[94. 24.  1.]]
onpick scatter: [3434] [[82. 43.  1.]]
onpick scatter: [3437] [[491.  65.   1.]]
onpick scatter: [3862] [[398.  54.   1.]]
onpick scatter: [3300] [[314.  56.   1.]]
onpick scatter: [4059] [[407.  73.   1.]]
onpick scatter: [1873] [[511.  93.   1.]]
onpick scatter: [3757] [[302.  84.   1.]]
onpick scatter: [3705] [[155.  84.   1.]]
onpick scatter: [1947] [[22. 89.  1.]]
onpick scatter: [3796] [[421. 104.   1.]]
onpick scatter: [3897] [[321. 118.   1.]]
onpick scatter: [3577] [[ 17. 125.   1.]]
onpick scatter: [3658] [[495. 148.   1.]]
onpick scatter: [3633] [[333. 150.   1.]]
onpick scatter: [2382] [[106. 137.   1.]]
onpick scatter: [4088] [[140. 146.   1.]]
onpick scatter: [3535] [[ 21. 145.   1.]]
onpick scatter: [4056] [[ 29. 150.   1.]]
onpi

In [8]:
manu_picks_to_(nimg, p, rlist, rind_list, extent=[[512, 1024], [0, 512]])

onpick scatter: [3748] [[358. 525.   1.]]
onpick scatter: [3106] [[280. 528.   1.]]
onpick scatter: [3440] [[224. 525.   1.]]
onpick scatter: [3531] [[261. 547.   1.]]
onpick scatter: [4103] [[404. 536.   1.]]
onpick scatter: [3564] [[476. 536.   1.]]
onpick scatter: [4127] [[493. 540.   1.]]
onpick scatter: [4115] [[391. 546.   1.]]
onpick scatter: [3677] [[142. 555.   1.]]
onpick scatter: [3800] [[ 43. 572.   1.]]
onpick scatter: [3510] [[ 97. 571.   1.]]
onpick scatter: [3488] [[241. 573.   1.]]
onpick scatter: [3941] [[403. 570.   1.]]
onpick scatter: [4044] [[432. 589.   1.]]
onpick scatter: [3268] [[160. 586.   1.]]
onpick scatter: [3620] [[ 95. 585.   1.]]
onpick scatter: [3845] [[ 65. 589.   1.]]
onpick scatter: [3343] [[  6. 614.   1.]]
onpick scatter: [3903] [[176. 617.   1.]]
onpick scatter: [1773] [[278. 623.   1.]]
onpick scatter: [2288] [[371. 617.   1.]]
onpick scatter: [4066] [[495. 635.   1.]]
onpick scatter: [3367] [[258. 633.   1.]]
onpick scatter: [3871] [[115. 636.

In [33]:
counts = 0

In [34]:
manu_picks_to_(nimg, p, rlist, rind_list, extent=[[0, 512], [512, 1024]])

onpick scatter no.1: [4011] [[875.  11.   1.]]
onpick scatter no.2: [3603] [[854.  10.   1.]]
onpick scatter no.3: [3077] [[527.  28.   1.]]
onpick scatter no.4: [3912] [[795.  24.   1.]]
onpick scatter no.5: [2593] [[839.  29.   1.]]
onpick scatter no.6: [3283] [[1.001e+03 3.000e+01 1.000e+00]]
onpick scatter no.7: [3601] [[1.019e+03 4.200e+01 1.000e+00]]
onpick scatter no.8: [4002] [[1.023e+03 4.400e+01 1.000e+00]]
onpick scatter no.9: [3860] [[836.  41.   1.]]
onpick scatter no.10: [3922] [[804.  42.   1.]]
onpick scatter no.11: [3544] [[1.008e+03 6.300e+01 1.000e+00]]
onpick scatter no.12: [4005] [[984.  62.   1.]]
onpick scatter no.13: [3356] [[637.  72.   1.]]
onpick scatter no.14: [3773] [[747.  70.   1.]]
onpick scatter no.15: [3704] [[874.  74.   1.]]
onpick scatter no.16: [3704] [[874.  74.   1.]]
onpick scatter no.17: [3773] [[747.  70.   1.]]
onpick scatter no.18: [3356] [[637.  72.   1.]]
onpick scatter no.19: [3890] [[532.  89.   1.]]
onpick scatter no.20: [4051] [[559.  

In [35]:
manu_picks_to_(nimg, p, rlist, rind_list, extent=[[512, 1024], [512, 1024]])

onpick scatter no.107: [3961] [[832. 523.   1.]]
onpick scatter no.108: [3485] [[586. 530.   1.]]
onpick scatter no.109: [4124] [[948. 540.   1.]]
onpick scatter no.110: [2650] [[959. 557.   1.]]
onpick scatter no.111: [3651] [[870. 556.   1.]]
onpick scatter no.112: [3673] [[722. 550.   1.]]
onpick scatter no.113: [2991] [[730. 559.   1.]]
onpick scatter no.114: [3404] [[556. 557.   1.]]
onpick scatter no.115: [4087] [[813. 573.   1.]]
onpick scatter no.116: [4065] [[931. 574.   1.]]
onpick scatter no.117: [4093] [[976. 590.   1.]]
onpick scatter no.118: [3899] [[576. 586.   1.]]
onpick scatter no.119: [3994] [[793. 605.   1.]]
onpick scatter no.120: [4112] [[895. 603.   1.]]
onpick scatter no.121: [3476] [[905. 605.   1.]]
onpick scatter no.122: [3215] [[837. 625.   1.]]
onpick scatter no.123: [3215] [[837. 625.   1.]]
onpick scatter no.124: [3509] [[515. 621.   1.]]
onpick scatter no.125: [3919] [[788. 628.   1.]]
onpick scatter no.126: [3270] [[786. 633.   1.]]
onpick scatter no.12

In [48]:
rind_list

[array([2890], dtype=int64),
 array([3457], dtype=int64),
 array([3455], dtype=int64),
 array([3751], dtype=int64),
 array([4038], dtype=int64),
 array([3768], dtype=int64),
 array([3434], dtype=int64),
 array([3437], dtype=int64),
 array([3862], dtype=int64),
 array([3300], dtype=int64),
 array([4059], dtype=int64),
 array([1873], dtype=int64),
 array([3757], dtype=int64),
 array([3705], dtype=int64),
 array([1947], dtype=int64),
 array([3796], dtype=int64),
 array([3897], dtype=int64),
 array([3577], dtype=int64),
 array([3658], dtype=int64),
 array([3633], dtype=int64),
 array([2382], dtype=int64),
 array([4088], dtype=int64),
 array([3535], dtype=int64),
 array([4056], dtype=int64),
 array([3467], dtype=int64),
 array([1071], dtype=int64),
 array([2984], dtype=int64),
 array([3745], dtype=int64),
 array([2418], dtype=int64),
 array([2240], dtype=int64),
 array([4014], dtype=int64),
 array([4058], dtype=int64),
 array([4064], dtype=int64),
 array([3713], dtype=int64),
 array([3734],

In [47]:
rind_list[187] = [888]

In [49]:
recycle_bin = []
arr = np.unique(np.array(rind_list, dtype=np.int64)).tolist()
real_rind = map(int, arr)
for i in real_rind:
    a = p[i]
    recycle_bin.append(a)
    
real_rind = map(int, arr)
ina = [i for i in real_rind]
whole_set = np.delete(p.copy(), ina, axis=0)

In [53]:
lattice_heavy = feature.blob_dog(nimg, threshold=.055, min_sigma=1, max_sigma=30, overlap=.01)
fig2, ax2 = plt.subplots()
ax2.plot(lattice_heavy[:, 1], lattice_heavy[:, 0], 'ro', alpha=.4, lw=1)
ax2.imshow(img, 'gray')
ax2.axis('off')
fig2.show()

In [57]:
media_set = list(whole_set)
l_ind = []
lattice_heavy_list = list(lattice_heavy)
ccounts = 0
for i in lattice_heavy_list:
    for index, element in enumerate(media_set):
        diff = np.sum((element - i)**2)
        if diff > 1e-18:
            #print(diff)
            continue
        else:
            l_ind.append(index)
            ccounts += 1
            #print(index)            

In [58]:
print(len(l_ind))
print(len(lattice_heavy))

781
782


In [59]:
lattice_light = np.delete(p.copy(), l_ind, axis=0)

In [60]:
def cross_rdf_cal(lattice_heavy, lattice_light, cellPara=[1024,1024], pixelSize=[1,1], bins=2048, unit='nm'):
    cellPara = np.array(cellPara, dtype='float64')
    pixelSize = np.array(pixelSize, dtype='float64')
    #realsize = np.array(cellPara, dtype='float64') * np.array(pixelSize, dtype='float64')
    dr = cellPara[0] / 2 / bins
    r = np.ones(bins) * dr * np.arange(1, bins+1)
    cross_g = np.zeros((bins, 2))
    cross_g[:, 0] = r
    from math import dist 
    for coords in lattice_light:
        for coords2 in lattice_heavy:
            distance = dist(coords, coords2)
            index = int(distance / dr)
            if 0 < index < bins:
                cross_g[index,1] += 2.0

    volume = np.zeros(bins)
    pi = np.pi
    for k in range(bins):
        r1 = k * dr
        r2 = r1 + dr
        s1 = 2 * pi * r1 **2
        s2 = 2 * pi * r2 **2
        volume[k] += s2 - s1
    cross_g[:,1] /= volume
    cross_g[:,0] *= pixelSize[0]
    max_peak = np.argmax(cross_g[:,1])
    max_val = np.max(cross_g[:,1])
    print(f'The highest peak is located at {max_peak * pixelSize[0]} nm with intensity of {max_val}')
    return cross_g

In [61]:
cross_g = cross_rdf_cal(lattice_heavy, lattice_light, pixelSize=[0.0178823, 0.0178823], bins=2048)

The highest peak is located at 1.2875256 nm with intensity of 22.90074988047784


In [68]:
fig4, ax4 = plt.subplots()
ax4.plot(cross_g[:, 0], cross_g[:, 1], 'k')
ax4.set_xlim([0, 2])
ax4.set_title(basename)
fig4.show()

In [64]:
basename, ext = os.path.splitext(os.path.basename(path[0]))
print(basename)
print(ext)

20200723 1347 STEM Diffraction HAADF 5.5 Mx_HAADF
.dm3


In [73]:
f = h5py.File('Gradient_1.hdf5', 'r+')

In [74]:
group1 = f.create_group(basename + '222')

In [75]:
group1['lattice_heavy'] = lattice_heavy
group1['lattice_light'] = lattice_light
group1['Micrograph_name'] = basename
group1['cross_g'] = cross_g

In [76]:
for na in f:
    print(na)

20200723 1347 STEM Diffraction HAADF 5.5 Mx_HAADF
20200723 1347 STEM Diffraction HAADF 5.5 Mx_HAADF222


In [77]:
f.close()

In [78]:
del group1